"""empty message

Revision ID: 41654dd64cb5
Revises: 68e2f85a7afe
Create Date: 2025-09-05 22:12:05.335226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41654dd64cb5'
down_revision = '68e2f85a7afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('branch_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
